version: '3.8'

services:
  flowpay-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_RABBITMQ_HOST: rabbitmq  # Definindo o host para o RabbitMQ
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: myuser  # Configuração do usuário
      SPRING_RABBITMQ_PASSWORD: secret  # Configuração da senha
    networks:
      - flowpay-network

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672:5672'  # Porta do RabbitMQ
      - '15672:15672'  # Porta de acesso à interface web
    networks:
      - flowpay-network  # Adicionando à mesma rede que o flowpay-app

networks:
  flowpay-network:
    driver: bridge  # Especificando o driver de rede para os contêineres
